name: "lint"

on:
  pull_request:
    branches: [main]
    paths:
      - "**.clj"
      - "**.edn"
      - "**.xml"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: clj-kondo
        uses: nnichols/clojure-lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
