name: "ci"

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.clj"
      - "**.edn"
      - "**.xml"
      - "**.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: 'echo "No build required" '

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  build:
    strategy:
      matrix:
        version: [11, 17]
    name: Build Ubuntu - Java
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
